const livros = [
  { titulo: 'Neuromancer', autor: 'William Gibson', genero: 'ficcao_cientifica' },
  { titulo: 'Duna', autor: 'Frank Herbert', genero: 'ficcao_cientifica' },
  { titulo: 'Pequenas Coisas Belas', autor: 'Cheryl Strayed', genero: 'inspiracional' },
  { titulo: 'O Senhor dos Anéis', autor: 'J.R.R. Tolkien', genero: 'fantasia' },
  { titulo: '1984', autor: 'George Orwell', genero: 'distopia' },
  { titulo: 'Cem Anos de Solidão', autor: 'Gabriel García Márquez', genero: 'realismo_magico' },
  { titulo: 'Dom Quixote', autor: 'Miguel de Cervantes', genero: 'classico' },
  { titulo: 'A Revolução dos Bichos', autor: 'George Orwell', genero: 'satira' },
  { titulo: 'O Hobbit', autor: 'J.R.R. Tolkien', genero: 'fantasia' },
  { titulo: 'Crime e Castigo', autor: 'Fiódor Dostoiévski', genero: 'classico' },
  { titulo: 'Matar um Rouxinol', autor: 'Harper Lee', genero: 'drama' },
  { titulo: 'O Sol é para Todos', autor: 'Harper Lee', genero: 'drama' },
  { titulo: 'A Guerra dos Tronos', autor: 'George R.R. Martin', genero: 'fantasia' },
  { titulo: 'A Mão Esquerda da Escuridão', autor: 'Ursula K. Le Guin', genero: 'ficcao_cientifica' },
  { titulo: 'A Menina que Roubava Livros', autor: 'Markus Zusak', genero: 'drama' },
  { titulo: 'A Culpa é das Estrelas', autor: 'John Green', genero: 'romance' },
  { titulo: 'O Código Da Vinci', autor: 'Dan Brown', genero: 'misterio' },
  { titulo: 'Harry Potter e a Pedra Filosofal', autor: 'J.K. Rowling', genero: 'fantasia' },
  { titulo: 'O Nome do Vento', autor: 'Patrick Rothfuss', genero: 'fantasia' },
  { titulo: 'O Poder do Hábito', autor: 'Charles Duhigg', genero: 'autoajuda' },
  { titulo: 'A Cor Púrpura', autor: 'Alice Walker', genero: 'drama' },
  { titulo: 'O Apanhador no Campo de Centeio', autor: 'J.D. Salinger', genero: 'classico' },
  { titulo: 'O Pequeno Príncipe', autor: 'Antoine de Saint-Exupéry', genero: 'infantil' },
  { titulo: 'A Revolta de Atlas', autor: 'Ayn Rand', genero: 'filosofia' },
  { titulo: 'A Arte da Guerra', autor: 'Sun Tzu', genero: 'estrategia' },
  { titulo: 'O Iluminado', autor: 'Stephen King', genero: 'terror' },
  { titulo: 'Orgulho e Preconceito', autor: 'Jane Austen', genero: 'romance' },
  { titulo: 'A Odisséia', autor: 'Homero', genero: 'classico' },
  { titulo: 'As Vinhas da Ira', autor: 'John Steinbeck', genero: 'drama' },
  { titulo: 'O Retrato de Dorian Gray', autor: 'Oscar Wilde', genero: 'classico' },
  { titulo: 'O Grande Gatsby', autor: 'F. Scott Fitzgerald', genero: 'drama' },
  { titulo: 'Os Miseráveis', autor: 'Victor Hugo', genero: 'classico' },
  { titulo: 'A Metamorfose', autor: 'Franz Kafka', genero: 'ficcao_cientifica' },
  { titulo: 'As Crônicas de Nárnia', autor: 'C.S. Lewis', genero: 'fantasia' },
  { titulo: 'O Principezinho', autor: 'Antoine de Saint-Exupéry', genero: 'infantil' },
  { titulo: 'O Alquimista', autor: 'Paulo Coelho', genero: 'espiritualidade' },
  { titulo: 'O Senhor das Moscas', autor: 'William Golding', genero: 'drama' },
  { titulo: 'Ulisses', autor: 'James Joyce', genero: 'classico' },
  { titulo: 'A Ilha do Tesouro', autor: 'Robert Louis Stevenson', genero: 'aventura' },
  { titulo: 'O Médico', autor: 'Noah Gordon', genero: 'historico' },
  { titulo: 'O Silmarillion', autor: 'J.R.R. Tolkien', genero: 'fantasia' },
  { titulo: 'Anna Karenina', autor: 'Liev Tolstói', genero: 'romance' },
  { titulo: 'O Monte dos Vendavais', autor: 'Emily Brontë', genero: 'classico' },
  { titulo: 'O Estrangeiro', autor: 'Albert Camus', genero: 'existencialismo' },
  { titulo: 'O Senhor das Sombras', autor: 'Cassandra Clare', genero: 'fantasia' },
  { titulo: 'A Sombra do Vento', autor: 'Carlos Ruiz Zafón', genero: 'misterio' },
  { titulo: 'A Revolta de Atlas', autor: 'Ayn Rand', genero: 'filosofia' },
  { titulo: 'O Ladrão de Raios', autor: 'Rick Riordan', genero: 'fantasia' },
  { titulo: 'A Moreninha', autor: 'Joaquim Manuel de Macedo', genero: 'romance' },
  { titulo: 'O Primo Basílio', autor: 'José Maria de Eça de Queirós', genero: 'realismo' },
  { titulo: 'O Guarani', autor: 'José de Alencar', genero: 'romance' },
  { titulo: 'O Cortiço', autor: 'Aluísio Azevedo', genero: 'naturalismo' },
  { titulo: 'O Ateneu', autor: 'Raul Pompeia', genero: 'realismo' },
]


module.exports = { livros }